CREATE TABLE IF NOT EXISTS functions (

    id INT AUTO_INCREMENT PRIMARY KEY,

    name VARCHAR(255) UNIQUE NOT NULL,

    runtime VARCHAR(50) NOT NULL,

    entrypoint VARCHAR(255) NOT NULL,

    image VARCHAR(255) NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);